[TRAVIS] clean-up

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -137,18 +137,15 @@ before_install:
       if [ $PYMVER == 2 ]; then
         PYINST=/System/Library/Frameworks/Python.framework/Versions/$PYMVER.7
         PY_EXE=$PYINST/bin/python2.7
+        # Next lines are not necessary if we give the actual path for the executable to cmake
         #BUILD_FLAGS="$BUILD_FLAGS -DPYTHON_LIBRARY=$PYINST/lib/libpython2.7.dylib"
         #BUILD_FLAGS="$BUILD_FLAGS -DPYTHON_INCLUDE_DIR=$PYINST/include/python2.7"
       else
-        brew upgrade python || travis_terminate 1
+        brew upgrade python || true # don't fail if upgrading doesn't do anything
         # find exact location of Python executable to pass to CMake
         # we attempt to find the last one if there are multiple Python 3 versions installed
-        find /usr/local/Cellar/python/ -type f -name python\* 
-        ls -d1 /usr/local/Cellar/python/$PYMVER.*/Frameworks/Python.framework/Versions/$PYMVER.*
         PY_INST=$(ls -d1 /usr/local/Cellar/python/$PYMVER.*/Frameworks/Python.framework/Versions/$PYMVER.*|tail -n 1)
-        echo XX${PY_INST}XX
         PYMVER=$(basename ${PY_INST})
-        echo PYMVER $PYMVER
         PY_EXE=$PY_INST/bin/python$PYMVER
         if [ ! -x "$PY_EXE" ]; then
           echo "Something wrong with finding Python executable for OSX"
@@ -171,10 +168,12 @@ before_install:
         brew install ccache
         # need curl to get pip and more recent cmake
         brew install curl
-        #brew install cmake
+        #brew install cmake # already present
+        # alternative: get our own
         #curl -0 https://cmake.org/files/v3.8/cmake-3.8.0-Darwin-x86_64.tar.gz -o cmake.tar.gz
         #tar xzf cmake.tar.gz
         #mv cmake-*/CMake.app/Contents/* cmake-*
+        #export PATH="$PWD/cmake-*/bin:$PATH"
       )
     elif [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
       PY_EXE=python$PYMVER
@@ -185,7 +184,6 @@ before_install:
       fi
     fi
  - echo "Using Python executable $PY_EXE"
- - cmake --version
  # get pip
  - curl -0 https://bootstrap.pypa.io/get-pip.py -o get-pip.py
  - $PY_EXE get-pip.py --user
@@ -199,17 +197,6 @@ before_install:
  - source github-stats/setup.sh
  # count unique clones, excluding travis, and print total
  - gh_stats_count -k uniques
- - |
-    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
-      # pip path fix
-      # show lib/site-packages path
-      $PY_EXE -m pydoc pip | grep -i -A 1 file
-      $PY_EXE -m pydoc codecov | grep -i -A 1 file
-      # append python bin dir to path (consult output from previous lines)
-      #pushd $HOME/Library/Python/$PYMVER*/bin
-      #export PATH="$PWD:$PATH"
-      #popd
-    fi
  - $PY_EXE --version
  - $PY_EXE -m pip --version
  - $PY_EXE -m pip freeze
@@ -222,7 +209,8 @@ before_install:
  - popd
  # N.B.: don't put into build matrix to allow caching.
  - BUILD_FLAGS="$BUILD_FLAGS -DPYVER=$PYMVER"
-
+ - cmake --version
+ 
 install:
  - |
     if [[ -n "$DOCKER_BUILD" ]]; then
