travis:tidy mostly whitespace

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,7 +1,13 @@
-# Language selection
 # Note: with `language: cpp`, `cache: ccache` works
 # but `cache: pip` and `python:` is ignored
 language: cpp
+dist: trusty  # Ubuntu 14.04 LTS
+sudo: required  # for docker
+services:
+- docker
+cache:  # shared between builds
+- ccache
+- pip
 
 # Currently commented out as set with environment flags
 # Both clang and gcc can be tested. More is the better.
@@ -80,226 +86,212 @@ matrix:
 
 env:
  global:
-  - BUILD_FLAGS="-DCMAKE_BUILD_TYPE=Release"
-  # don't use too many threads - may crash
-  - MAKEFLAGS="-j 2"
-
-# Ubuntu 14.04 LTS
-dist: trusty
-
-# sudo required for docker
-sudo: required
-services:
- - docker
+ - BUILD_FLAGS="-DCMAKE_BUILD_TYPE=Release"
+ - MAKEFLAGS="-j 2"  # too many threads may crash
 
 # Compilation dependencies
 addons:
  apt:
   sources:
-   - ubuntu-toolchain-r-test
+  - ubuntu-toolchain-r-test
   packages:
-   - git-core
-   - build-essential
-   - g++-6
-   - g++-7
-   - libboost-all-dev
-   - libhdf5-serial-dev
-   - libfftw3-dev
-   - python-dev
-   - python3-dev
-   - python-tk
-   - python3-tk
-   - libopenblas-dev
-   - libatlas-base-dev
-   - liblapack-dev
-   - libxml2-dev
-   - libarmadillo-dev
-   - libgtest-dev
-   - libplplot-dev
-   - swig
-   - ccache
-   # for building ACE (note: Trusty only)
-   - realpath
-   # not in whitelist
-   - libxslt-dev
-   - libace-dev
-   # - root-system-bin
-
-# cache C/C++/pip
-cache:
+  - git-core
+  - build-essential
+  - g++-6
+  - g++-7
+  - libboost-all-dev
+  - libhdf5-serial-dev
+  - libfftw3-dev
+  - python-dev
+  - python3-dev
+  - python-tk
+  - python3-tk
+  - libopenblas-dev
+  - libatlas-base-dev
+  - liblapack-dev
+  - libxml2-dev
+  - libarmadillo-dev
+  - libgtest-dev
+  - libplplot-dev
+  - swig
   - ccache
-  - pip
+  # for building ACE (note: Trusty only)
+  - realpath
+  # not in whitelist
+  - libxslt-dev
+  - libace-dev
+  # - root-system-bin
 
 before_install:
- # Set C and C++ compiler etc using trick from
- # https://docs.travis-ci.com/user/languages/cpp/#c11c11-and-beyond-and-toolchain-versioning
- - eval "${MATRIX_EVAL}"
- - $CC --version
- - $CXX --version
- - mkdir -p ~/.local/bin
- - pushd ~/.local/bin
- # Note: use ( set -ev; ... ) to echo commands and exit immediately on failure
- # in compounds statements (note that export/cd etc won't persist).
- - |
-    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
-      brew update
-      BUILD_FLAGS="$BUILD_FLAGS -DSHARED_LIBS_ABS_PATH=ON"
-      brew install openblas
-      # Get openblas version
-      blas_ver=$(brew list --versions openblas)
-      blas_ver=${blas_ver#"openblas "}
-      EXTRA_BUILD_FLAGS="$EXTRA_BUILD_FLAGS -DCBLAS_INCLUDE_DIR=/usr/local/Cellar/openblas/${blas_ver}/include -DCBLAS_LIBRARY=/usr/local/Cellar/openblas/${blas_ver}/lib/libblas.dylib"
-      if [ $PYMVER == 2 ]; then
-        PYINST=/System/Library/Frameworks/Python.framework/Versions/$PYMVER.7
-        PY_EXE=$PYINST/bin/python2.7
-        # Next lines are not necessary if we give the actual path for the executable to cmake
-        #BUILD_FLAGS="$BUILD_FLAGS -DPYTHON_LIBRARY=$PYINST/lib/libpython2.7.dylib"
-        #BUILD_FLAGS="$BUILD_FLAGS -DPYTHON_INCLUDE_DIR=$PYINST/include/python2.7"
-      else
-        brew upgrade python || true # don't fail if upgrading doesn't do anything
-        # find exact location of Python executable to pass to CMake
-        # we attempt to find the last one if there are multiple Python 3 versions installed
-        PY_INST=$(ls -d1 /usr/local/Cellar/python/$PYMVER.*/Frameworks/Python.framework/Versions/$PYMVER.*|tail -n 1)
-        PYMVER=$(basename ${PY_INST})
-        PY_EXE=$PY_INST/bin/python$PYMVER
-        if [ ! -x "$PY_EXE" ]; then
-          echo "Something wrong with finding Python executable for OSX"
-          echo "PY_EXE = $PY_EXE"
-          travis_terminate 1
-        fi
-        # Next lines are not necessary if we give the actual path for the executable to cmake
-        #PY_LIB=$PY_INST/Python
-        #PY_INC=$PY_INST/Headers
-        # BUILD_FLAGS="$BUILD_FLAGS -DPYTHON_LIBRARY=$PY_LIB -DPYTHON_INCLUDE_DIR=$PY_INC"
-      fi
-      BUILD_FLAGS="$BUILD_FLAGS -DPYTHON_EXECUTABLE=$PY_EXE"
-      ( set -ev
-        # boost is already installed but 1.65 doesn't work so update
-        brew reinstall boost
-        # we currently need boost-python
-        # brew install boost-python
-        brew install ace
-        brew install swig
-        brew install ccache
-        if [[ $EXTRA_BUILD_FLAGS == *"SYSTEM_FFTW3=ON"* ]]; then
-            brew install fftw
-        else
-            echo "Not installing FFTW as we are building it"
-        fi
-        # need curl to get pip and more recent cmake
-        brew install curl
-        #brew install cmake # already present
-        # alternative: get our own
-        #curl -L -O https://github.com/Kitware/CMake/releases/download/v3.13.4/cmake-3.13.4-Darwin-x86_64.tar.gz
-        #tar xzf cmake-*.tar.gz
-        #mv cmake-*/CMake.app/Contents/* cmake
-        #export PATH="$PWD/cmake/bin:$PATH"
-      )
-    elif [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
-      PY_EXE=python$PYMVER
-      if [[ -z "$DOCKER_BUILD" ]]; then
-        curl -o cmake.tgz -L https://github.com/Kitware/CMake/releases/download/v3.13.4/cmake-3.13.4-Linux-x86_64.tar.gz
-        tar xzf cmake.tgz && rm cmake.tgz
-        ln -s cmake-*x86_64 cmake
-        export PATH="$PWD/cmake/bin:$PATH"
-      fi
-    fi
- - echo "Using Python executable $PY_EXE"
- # get pip
- - curl -0 https://bootstrap.pypa.io/get-pip.py -o get-pip.py
- - $PY_EXE get-pip.py --user
- # setuptools may be out of date on osx
- - $PY_EXE -m pip install --user -U pip setuptools wheel
- # ensure python bin dir exists (and coverage dependencies installed)
- - $PY_EXE -m pip install --user -U nose codecov coveralls
- # for counting clones, excluding ours
- - |
-    if [[ -n "$GITHUB_API_TOKEN" ]]; then
-      git clone https://$GITHUB_API_TOKEN@github.com/ccp-petmr-codebot/github-stats --branch $TRAVIS_REPO_SLUG
-      # update with last fortnight's clones from GitHub API
-      source github-stats/setup.sh
-      # count unique clones, excluding travis, and print total
-      gh_stats_count -k uniques
-    fi
- - $PY_EXE --version
- - $PY_EXE -m pip --version
- - $PY_EXE -m pip freeze
- # ccache compiler override
- - ln -s "$(which ccache)" g++
- - ln -s "$(which ccache)" g++-6
- - ln -s "$(which ccache)" g++-7
- - ln -s "$(which ccache)" gcc
- - ln -s "$(which ccache)" gcc-6
- - ln -s "$(which ccache)" gcc-7
- - export PATH="$PWD:$PATH"
- - popd
- # N.B.: don't put into build matrix to allow caching.
- - BUILD_FLAGS="$BUILD_FLAGS -DPYVER=$PYMVER"
- - cmake --version
+# Set C and C++ compiler etc using trick from
+# https://docs.travis-ci.com/user/languages/cpp/#c11c11-and-beyond-and-toolchain-versioning
+- eval "${MATRIX_EVAL}"
+- $CC --version
+- $CXX --version
+- mkdir -p ~/.local/bin
+- pushd ~/.local/bin
+# Note: use ( set -ev; ... ) to echo commands and exit immediately on failure
+# in compounds statements (note that export/cd etc won't persist).
+- |
+   if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
+     brew update
+     BUILD_FLAGS="$BUILD_FLAGS -DSHARED_LIBS_ABS_PATH=ON"
+     brew install openblas
+     # Get openblas version
+     blas_ver=$(brew list --versions openblas)
+     blas_ver=${blas_ver#"openblas "}
+     EXTRA_BUILD_FLAGS="$EXTRA_BUILD_FLAGS -DCBLAS_INCLUDE_DIR=/usr/local/Cellar/openblas/${blas_ver}/include -DCBLAS_LIBRARY=/usr/local/Cellar/openblas/${blas_ver}/lib/libblas.dylib"
+     if [ $PYMVER == 2 ]; then
+       PYINST=/System/Library/Frameworks/Python.framework/Versions/$PYMVER.7
+       PY_EXE=$PYINST/bin/python2.7
+       # Next lines are not necessary if we give the actual path for the executable to cmake
+       #BUILD_FLAGS="$BUILD_FLAGS -DPYTHON_LIBRARY=$PYINST/lib/libpython2.7.dylib"
+       #BUILD_FLAGS="$BUILD_FLAGS -DPYTHON_INCLUDE_DIR=$PYINST/include/python2.7"
+     else
+       brew upgrade python || true # don't fail if upgrading doesn't do anything
+       # find exact location of Python executable to pass to CMake
+       # we attempt to find the last one if there are multiple Python 3 versions installed
+       PY_INST=$(ls -d1 /usr/local/Cellar/python/$PYMVER.*/Frameworks/Python.framework/Versions/$PYMVER.*|tail -n 1)
+       PYMVER=$(basename ${PY_INST})
+       PY_EXE=$PY_INST/bin/python$PYMVER
+       if [ ! -x "$PY_EXE" ]; then
+         echo "Something wrong with finding Python executable for OSX"
+         echo "PY_EXE = $PY_EXE"
+         travis_terminate 1
+       fi
+       # Next lines are not necessary if we give the actual path for the executable to cmake
+       #PY_LIB=$PY_INST/Python
+       #PY_INC=$PY_INST/Headers
+       # BUILD_FLAGS="$BUILD_FLAGS -DPYTHON_LIBRARY=$PY_LIB -DPYTHON_INCLUDE_DIR=$PY_INC"
+     fi
+     BUILD_FLAGS="$BUILD_FLAGS -DPYTHON_EXECUTABLE=$PY_EXE"
+     ( set -ev
+       # boost is already installed but 1.65 doesn't work so update
+       brew reinstall boost
+       # we currently need boost-python
+       # brew install boost-python
+       brew install ace
+       brew install swig
+       brew install ccache
+       if [[ $EXTRA_BUILD_FLAGS == *"SYSTEM_FFTW3=ON"* ]]; then
+           brew install fftw
+       else
+           echo "Not installing FFTW as we are building it"
+       fi
+       # need curl to get pip and more recent cmake
+       brew install curl
+       #brew install cmake # already present
+       # alternative: get our own
+       #curl -L -O https://github.com/Kitware/CMake/releases/download/v3.13.4/cmake-3.13.4-Darwin-x86_64.tar.gz
+       #tar xzf cmake-*.tar.gz
+       #mv cmake-*/CMake.app/Contents/* cmake
+       #export PATH="$PWD/cmake/bin:$PATH"
+     )
+   elif [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
+     PY_EXE=python$PYMVER
+     if [[ -z "$DOCKER_BUILD" ]]; then
+       curl -o cmake.tgz -L https://github.com/Kitware/CMake/releases/download/v3.13.4/cmake-3.13.4-Linux-x86_64.tar.gz
+       tar xzf cmake.tgz && rm cmake.tgz
+       ln -s cmake-*x86_64 cmake
+       export PATH="$PWD/cmake/bin:$PATH"
+     fi
+   fi
+- echo "Using Python executable $PY_EXE"
+# get pip
+- curl -0 https://bootstrap.pypa.io/get-pip.py -o get-pip.py
+- $PY_EXE get-pip.py --user
+# setuptools may be out of date on osx
+- $PY_EXE -m pip install --user -U pip setuptools wheel
+# ensure python bin dir exists (and coverage dependencies installed)
+- $PY_EXE -m pip install --user -U nose codecov coveralls
+# for counting clones, excluding ours
+- |
+   if [[ -n "$GITHUB_API_TOKEN" ]]; then
+     git clone https://$GITHUB_API_TOKEN@github.com/ccp-petmr-codebot/github-stats --branch $TRAVIS_REPO_SLUG
+     # update with last fortnight's clones from GitHub API
+     source github-stats/setup.sh
+     # count unique clones, excluding travis, and print total
+     gh_stats_count -k uniques
+   fi
+- $PY_EXE --version
+- $PY_EXE -m pip --version
+- $PY_EXE -m pip freeze
+# ccache compiler override
+- ln -s "$(which ccache)" g++
+- ln -s "$(which ccache)" g++-6
+- ln -s "$(which ccache)" g++-7
+- ln -s "$(which ccache)" gcc
+- ln -s "$(which ccache)" gcc-6
+- ln -s "$(which ccache)" gcc-7
+- export PATH="$PWD:$PATH"
+- popd
+# N.B.: don't put into build matrix to allow caching.
+- BUILD_FLAGS="$BUILD_FLAGS -DPYVER=$PYMVER"
+- cmake --version
 
 install:
- - |
-    if [[ -n "$DOCKER_BUILD" ]]; then
-      cd docker
-      export DCC="docker-compose -p "travis_${TRAVIS_JOB_NUMBER/./_}" -f $PWD/docker-compose.yml"
-      [[ "$DOCKER_BUILD" == *"DEVEL"* ]] && export DCC="$DCC -f $PWD/docker-compose.devel.yml"
-      [[ "$DOCKER_BUILD" == *"SERVICE"* ]] && export DCC="$DCC -f $PWD/docker-compose.srv.yml"
-      ( set -ev
-        # pull previous base image for its layer cache
-        docker pull ccppetmr/sirf:core
-        # count the docker pull (prefix `d`)
-        [[ -n "$GITHUB_API_TOKEN" ]] && gh_stats_count -k uniques --decrement -pd
-        # rebuild base image (using above docker cache)
-        # and sirf image (with travis' ccache)
-        rm -rf devel/.ccache
-        if [[ -n "$DOCKER_RECREATE_CCACHE" ]]; then
-          mkdir devel/.ccache
-          sudo rm -rf ~/.ccache
-        else
-          mv ~/.ccache devel/
-        fi
-        $DCC build --pull core
-        # don't count the extra clone we're about to do
-        # TODO: Do we need this? Is docker a distinct cloner from travis?
-        # cloners_count_decrement
-        $DCC build sirf
-        # extract updated ccache
-        sudo rm -rf devel/.ccache/*
-        $DCC run --rm sirf /bin/bash -c 'sudo cp -a /opt/ccache/* /devel/.ccache/'
-        # replace travis' ccache with the built images's
-        mv devel/.ccache ~
-      )
-    else
-      ( set -ev
-        $PY_EXE -m pip install --user --only-binary=numpy,scipy,matplotlib numpy scipy matplotlib
-        cmake $BUILD_FLAGS $EXTRA_BUILD_FLAGS .
-        # Job may timeout (>50min) if no ccache, otherwise should be <1min:
-        make
-        mv INSTALL/share/gadgetron/config/gadgetron.xml.example INSTALL/share/gadgetron/config/gadgetron.xml
-      ) || travis_terminate 1
-      source $PWD/INSTALL/bin/env_ccppetmr.sh
-    fi
+- |
+   if [[ -n "$DOCKER_BUILD" ]]; then
+     cd docker
+     export DCC="docker-compose -p "travis_${TRAVIS_JOB_NUMBER/./_}" -f $PWD/docker-compose.yml"
+     [[ "$DOCKER_BUILD" == *"DEVEL"* ]] && export DCC="$DCC -f $PWD/docker-compose.devel.yml"
+     [[ "$DOCKER_BUILD" == *"SERVICE"* ]] && export DCC="$DCC -f $PWD/docker-compose.srv.yml"
+     ( set -ev
+       # pull previous base image for its layer cache
+       docker pull ccppetmr/sirf:core
+       # count the docker pull (prefix `d`)
+       [[ -n "$GITHUB_API_TOKEN" ]] && gh_stats_count -k uniques --decrement -pd
+       # rebuild base image (using above docker cache)
+       # and sirf image (with travis' ccache)
+       rm -rf devel/.ccache
+       if [[ -n "$DOCKER_RECREATE_CCACHE" ]]; then
+         mkdir devel/.ccache
+         sudo rm -rf ~/.ccache
+       else
+         mv ~/.ccache devel/
+       fi
+       $DCC build --pull core
+       # don't count the extra clone we're about to do
+       # TODO: Do we need this? Is docker a distinct cloner from travis?
+       # cloners_count_decrement
+       $DCC build sirf
+       # extract updated ccache
+       sudo rm -rf devel/.ccache/*
+       $DCC run --rm sirf /bin/bash -c 'sudo cp -a /opt/ccache/* /devel/.ccache/'
+       # replace travis' ccache with the built images's
+       mv devel/.ccache ~
+     )
+   else
+     ( set -ev
+       $PY_EXE -m pip install --user --only-binary=numpy,scipy,matplotlib numpy scipy matplotlib
+       cmake $BUILD_FLAGS $EXTRA_BUILD_FLAGS .
+       # Job may timeout (>50min) if no ccache, otherwise should be <1min:
+       make
+       mv INSTALL/share/gadgetron/config/gadgetron.xml.example INSTALL/share/gadgetron/config/gadgetron.xml
+     ) || travis_terminate 1
+     source $PWD/INSTALL/bin/env_ccppetmr.sh
+   fi
 
 script:
- - |
-    if [[ -n "$DOCKER_BUILD" ]]; then
-      # run tests within the container
-      $DCC run --rm sirf /bin/bash --login -c '/devel/test.sh 1'
-    else
-      ./INSTALL/bin/gadgetron >& gadgetron.log&
-      # print for debugging
-      cat builds/SIRF/build/CMakeCache.txt
-      ctest --output-on-failure; test_fail=$?
-      # echo "----------- Killing gadgetron server"
-      # killall gadgetron
-      if [[ $test_fail -ne 0 ]]; then
-        #echo "----------- Test output"
-        # cat builds/SIRF/build/Testing/Temporary/LastTest.log
-        echo "----------- Last 70 lines of gadgetron.log"
-        tail -n 70 gadgetron.log
-        travis_terminate $test_fail
-      fi
-    fi
+- |
+   if [[ -n "$DOCKER_BUILD" ]]; then
+     # run tests within the container
+     $DCC run --rm sirf /bin/bash --login -c '/devel/test.sh 1'
+   else
+     ./INSTALL/bin/gadgetron >& gadgetron.log&
+     # print for debugging
+     cat builds/SIRF/build/CMakeCache.txt
+     ctest --output-on-failure; test_fail=$?
+     # echo "----------- Killing gadgetron server"
+     # killall gadgetron
+     if [[ $test_fail -ne 0 ]]; then
+       #echo "----------- Test output"
+       # cat builds/SIRF/build/Testing/Temporary/LastTest.log
+       echo "----------- Last 70 lines of gadgetron.log"
+       tail -n 70 gadgetron.log
+       travis_terminate $test_fail
+     fi
+   fi
 
 after_success:
 - |
